---
apiVersion: v2
kind: TopicTemplate
metadata:
    labels:
        category: template
    name: high-partition-topic
spec:
    defaults:
        metadata:
            labels:
                throughput: high
            name: my-topic-$${department}
        spec:
            configs:
                cleanup.policy: delete
                min.insync.replicas: "2"
                retention.ms: "604800000"
            partitions: 24
            replicationFactor: 3
    description: Optimised for high-throughput workloads. 24 partitions, 3× replication, 7-day retention.
    displayName: High Partition Topic

