# topics.yml
---
apiVersion: v2
kind: Topic
metadata:
  name: abcd.topic
  cluster: my-cluster
spec:
  replicationFactor: 1
  partitions: 3
  configs:
    min.insync.replicas: 1
    cleanup.policy: delete
    retention.ms: 604800000
---
apiVersion: v2
kind: Topic
metadata:
  name: abcd.myTopicWrong
  cluster: my-cluster
spec:
  replicationFactor: 1
  partitions: 3
  configs:
    min.insync.replicas: 1
    cleanup.policy: delete
    retention.ms: 604800000
