---
apiVersion: gateway/v2
kind: VirtualCluster
metadata:
  name: vcluster1
spec:
  prefix: vcluster1
---
apiVersion: gateway/v2
kind: VirtualCluster
metadata:
  name: vcluster2
spec:
  prefix: vcluster2
---
apiVersion: gateway/v2
kind: AliasTopic
metadata:
  name: alias1
  vCluster: vcluster1
spec:
  physicalName: vcluster1backtopic
---
apiVersion: gateway/v2
kind: AliasTopic
metadata:
  name: alias2
  vCluster: vcluster1
spec:
  physicalName: vcluster1backtopic
---
apiVersion: gateway/v2
kind: AliasTopic
metadata:
  name: alias
spec:
  physicalName: vcluster1backtopic
---
apiVersion: gateway/v2
kind: ConcentrationRule
metadata:
  name: rule1
  vCluster: vcluster1
spec:
  pattern: toto.*
  physicalTopics:
    delete: yolo
  autoManaged: true
---
apiVersion: gateway/v2
kind: ConcentrationRule
metadata:
  name: rule2
  vCluster: vcluster1
spec:
  pattern: toto.*
  physicalTopics:
    delete: yolo
---
apiVersion: gateway/v2
kind: GatewayGroup
metadata:
  name: group1
spec:
  members:
    - vCluster: vcluster1
      name: toto1
  externalGroups: ["ext_g1", "ext_g2"]
---
apiVersion: gateway/v2
kind: GatewayGroup
metadata:
  name: group2
spec:
  members:
    - vCluster: vcluster3
      name: toto1
  externalGroups: ["ext_g1", "ext_g2"]
---
kind: Interceptor
apiVersion: gateway/v2
metadata:
  name: enforce-partition-limit
spec:
  pluginClass: "io.conduktor.gateway.interceptor.safeguard.ReadOnlyTopicPolicyPlugin"
  priority: 100
  config:
    topic: "client_topic_toto"
    action: "BLOCK"
---
kind: Interceptor
apiVersion: gateway/v2
metadata:
  name: fieldlevelencryption
  scope:
    vCluster: vcluster1
    username: toto
spec:
  pluginClass: "io.conduktor.gateway.interceptor.EncryptPlugin"
  priority: 100
  config: {
    "schemaRegistryConfig": {
      "host": "http://localhost:8081"
    },
    "fields": [
      {
        "fieldName": "number",
        "keySecretId": "number-secret"
      },
      {
        "fieldName": "shipping_address",
        "keySecretId": "shipping_address-secret"
      }
    ]
  }
---
apiVersion: gateway/v2
kind: GatewayServiceAccount
metadata:
  name: user1
spec:
  type: Local
---
apiVersion: gateway/v2
kind: GatewayServiceAccount
metadata:
  name: user1
  vCluster: vcluster1
spec:
  type: Local
---
apiVersion: gateway/v2
kind: GatewayServiceAccount
metadata:
  name: user1
  vCluster: vcluster1
spec:
  type: Local
---
apiVersion: gateway/v2
kind: GatewayServiceAccount
metadata:
  name: user2
  vCluster: vcluster1
spec:
  type: External
  externalNames:
    - ext_user2
