name: Build Docker Images

on:
  workflow_call:
    inputs:
      image_tags:
        required: true
        type: string
        description: (string) Image tags to build in docker/metadata-action format
      release:
        required: false
        type: boolean
        description: (bool) Whether this is a release or not
        default: false
      push:
        required: false
        type: boolean
        description: (bool) Whether we should push the image or not
        default: true
env:
  NAMESPACE: "conduktor"
  LABEL_IMAGE_AUTHORS: "Conduktor <support@conduktor.io>"
  LABEL_IMAGE_DOCUMENTATION: "https://docs.conduktor.io/conduktor"
  LABEL_IMAGE_VENDOR: "Conduktor.io"

jobs:
  build-docker:
    name: Build Platform Docker
    runs-on: [cdk-standard]
    permissions:
      id-token: write
      contents: read
    env:
      IMAGE_NAME: "conduktorctl"
      HARBOR_IMAGE: "harbor.cdkt.dev/conduktor/conduktorctl"
      LABEL_IMAGE_TITLE: "Conduktor ctl"
      LABEL_IMAGE_DESCRIPTION: "Conduktor command line tools"
      LABEL_IMAGE_URL: "https://hub.docker.com/r/conduktor/conduktorctl"
    steps:
      - name: Set up Docker Buildx
        id: setup-buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.9.1
          install: true
          platforms: linux/amd64,linux/arm64

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Docker multi registries configuration
        id: docker_meta
        uses: conduktor/conduktor-actions/docker-multi-registries@v3.0.0
        with:
          image-name: |
            ${{ env.IMAGE_NAME }}
          namespace: ${{ env.NAMESPACE }}
          tags: ${{ inputs.image_tags }}
          labels: |
            org.opencontainers.image.title=${{ env.LABEL_IMAGE_TITLE }}
            org.opencontainers.image.description=${{ env.LABEL_IMAGE_DESCRIPTION }}
            org.opencontainers.image.authors=${{ env.LABEL_IMAGE_AUTHORS }}
            org.opencontainers.image.documentation=${{ env.LABEL_IMAGE_DOCUMENTATION }}
            org.opencontainers.image.vendor=${{ env.LABEL_IMAGE_VENDOR }}
            org.opencontainers.image.url=${{ env.LABEL_IMAGE_URL }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ github.event.release.tag_name || github.ref_name }}
      - uses: actions/checkout@v3
      - name: Build ${{ env.IMAGE_NAME }} for ${{ steps.buildx.outputs.platforms }}
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ inputs.push }}
          file: docker/Dockerfile
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=registry,ref=${{env.HARBOR_IMAGE}}:main
          cache-to: type=inline,mode=min
          github-token: ${{ secrets.GITHUB_TOKEN }}
          build-args: |
            hash=${{ github.sha }}
            version=${{ github.event.release.tag_name || github.ref_name }}